# Copyright (C) 2019 The MoKee Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/taurus/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/taurus

PRODUCT_COPY_FILES += \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libaudcal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudcal.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_imx132_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx132_default_video.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_imx132_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx132_preview.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_imx132_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx132_zsl.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_imx175_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175_default_video.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_imx175_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175_hfr_120fps.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_imx175_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175_hfr_60fps.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_imx175_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175_hfr_90fps.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_imx175_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175_preview.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_imx175_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175_zsl.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_imx175l_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175l_default_video.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_imx175l_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175l_hfr_120fps.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_imx175l_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175l_hfr_60fps.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_imx175l_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175l_hfr_90fps.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_imx175l_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175l_preview.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_imx175l_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx175l_zsl.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_s5k3h7a_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h7a_default_video.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_s5k3h7a_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h7a_hfr_120fps.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_s5k3h7a_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h7a_hfr_60fps.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_s5k3h7a_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h7a_hfr_90fps.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_s5k3h7a_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h7a_preview.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libchromatix_s5k3h7a_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h7a_zsl.so \
    vendor/xiaomi/taurus/proprietary/vendor/lib/libcsd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcsd-client.so \
    vendor/xiaomi/taurus/proprietary/vendor/firmware/libpn544_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn544_fw.so
